version: '3'

services:
  mysql:
    image: "mysql:5.7"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../wp-content/mysql.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - mysql
    image: "wordpress:php7.0"
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - wp_data:/var/www/html
      - ./htaccess:/var/www/html/.htaccess
      - ../wp-content:/var/www/html/wp-content
    restart: always
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  wp:
    depends_on:
      - mysql
    image: "wordpress:cli-php7.0"
    volumes:
      - wp_data:/var/www/html

volumes:
  mysql_data:
  wp_data:
